# Generated by Django 6.0.6 on 2026-06-09 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('winner', models.BooleanField(default=False)),
                ('customer_name', models.CharField(blank=True, max_length=500)),
                ('customer_bin', models.CharField(blank=True, max_length=12)),
                ('contract_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='companies.supplier')),
            ],
            options={
                'ordering': ['-contract_date'],
            },
        ),
    ]
