# Generated by Django 6.0.6 on 2026-06-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='tender_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
