# Generated by Django 6.0.6 on 2026-06-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_gos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
