# Generated by Django 6.0.6 on 2026-10-05 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_supplier_is_customer_supplier_is_supplier'),
        ('contracts', '0005_fix_unique_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='companies.supplier'),
        ),
    ]
