# Generated by Django 6.0.6 on 2026-06-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='director_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
