# Generated by Django 6.0.6 on 2026-06-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_supplier_director_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='adata_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
