# Generated by Django 6.0.6 on 2026-06-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_supplier_adata_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='company_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='oked',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
