# Generated by Django 6.0.6 on 2026-06-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_supplier_company_status_supplier_oked'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='company_size',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='supplier',
            name='economic_sector',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='supplier',
            name='kopf',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='supplier',
            name='resident_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
