# Generated by Django 6.0.6 on 2026-10-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_supplier_company_size_supplier_economic_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_customer',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_supplier',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
