# Generated by Django 6.0.6 on 2026-06-09 06:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('total_contract_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('explanation', models.TextField(blank=True)),
                ('ai_explanation', models.TextField(blank=True)),
                ('last_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suppliers', models.ManyToManyField(related_name='risk_clusters', to='companies.supplier')),
            ],
            options={
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('owner', 'Common Owner'), ('director', 'Common Director'), ('address', 'Common Address'), ('phone', 'Common Phone'), ('email', 'Common Email')], max_length=20)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='companies.supplier')),
                ('target_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='companies.supplier')),
            ],
            options={
                'indexes': [models.Index(fields=['connection_type'], name='graph_conne_connect_a7a985_idx')],
            },
        ),
    ]
