# Generated by Django 6.0.6 on 2026-10-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_cluster_analysis_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection_type',
            field=models.CharField(choices=[('owner', 'Common Owner'), ('director', 'Common Director'), ('address', 'Common Address'), ('phone', 'Common Phone'), ('email', 'Common Email'), ('customer', 'Shared customer')], max_length=20),
        ),
    ]
