# Generated by Django 6.0.6 on 2026-10-06 12:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_supplier_is_customer_supplier_is_supplier'),
        ('graph', '0004_english_display_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('source_key', models.CharField(max_length=100)),
                ('target_key', models.CharField(db_index=True, max_length=100)),
                ('relationship_type', models.CharField(db_index=True, max_length=20)),
                ('semantic_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_edges', to='companies.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='GraphInputState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64)),
                ('feature_keys', models.JSONField(default=list)),
                ('algorithm_version', models.CharField(max_length=30)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='graph_input_state', to='companies.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='GraphSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('graph_hash', models.CharField(max_length=64)),
                ('algorithm_version', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('active', 'Active'), ('retired', 'Retired'), ('legacy', 'Legacy')], max_length=12)),
                ('as_of', models.DateField()),
                ('member_ids', models.JSONField(default=list)),
                ('payload', models.JSONField(default=dict)),
                ('changes', models.JSONField(default=dict)),
                ('legacy_explanation', models.TextField(blank=True)),
                ('legacy_explanation_fingerprint', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='graph.riskcluster')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_versions', to='graph.graphsnapshot')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='ClusterLineage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('shared_member_ids', models.JSONField(default=list)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transitions', to='graph.graphsnapshot')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transitions', to='graph.graphsnapshot')),
            ],
        ),
        migrations.AddField(
            model_name='riskcluster',
            name='current_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='graph.graphsnapshot'),
        ),
        migrations.CreateModel(
            name='GraphViewState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graph.riskcluster')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graph.graphsnapshot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GraphRebuildJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dedup_key', models.CharField(max_length=64)),
                ('supplier_ids', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('summary', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('dedup_key',), name='graph_active_job_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='graphsnapshot',
            constraint=models.UniqueConstraint(fields=('cluster', 'version'), name='graph_snapshot_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='clusterlineage',
            constraint=models.UniqueConstraint(fields=('source', 'target'), name='graph_lineage_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='graphviewstate',
            constraint=models.UniqueConstraint(fields=('user', 'cluster'), name='graph_personal_view_unique'),
        ),
    ]
