# Generated by Django 6.0.6 on 2026-10-05 16:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_supplier_is_customer_supplier_is_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='same_name', max_length=40)),
                ('confidence', models.DecimalField(decimal_places=3, default='0.250', max_digits=4)),
                ('status', models.CharField(choices=[('pending', 'Требует проверки'), ('rejected', 'Разные люди'), ('confirmed', 'Подтверждено')], default='pending', max_length=20)),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('mode', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('succeeded', 'Завершён'), ('failed', 'Ошибка'), ('partial', 'Частично завершён')], db_index=True, default='running', max_length=20)),
                ('stage', models.CharField(default='contracts', max_length=20)),
                ('options', models.JSONField(default=dict)),
                ('next_page', models.PositiveIntegerField(default=1)),
                ('offset', models.PositiveIntegerField(default=0)),
                ('page_fingerprint', models.CharField(blank=True, max_length=64)),
                ('enrichment_cursor', models.PositiveBigIntegerField(default=0)),
                ('counters', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonSourceIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('source_key', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=20)),
                ('observed_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SelectedFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SourceCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('stream', models.CharField(max_length=20)),
                ('next_page', models.PositiveIntegerField(default=1)),
                ('offset', models.PositiveIntegerField(default=0)),
                ('page_fingerprint', models.CharField(blank=True, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('subject_key', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('raw_values', models.JSONField(default=dict)),
                ('normalized_values', models.JSONField(default=dict)),
                ('parser_version', models.CharField(max_length=40)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('observed_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('fingerprint', models.CharField(max_length=64)),
                ('from_cache', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionLease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.ingestionrun')),
            ],
        ),
        migrations.CreateModel(
            name='IngestionIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=40)),
                ('subject_key', models.CharField(max_length=255)),
                ('stage', models.CharField(max_length=20)),
                ('error_code', models.CharField(max_length=80)),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='companies.supplier')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='ingestion.ingestionrun')),
            ],
        ),
    ]
