# Generated by Django 6.0.6 on 2026-10-05 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_supplier_is_customer_supplier_is_supplier'),
        ('contracts', '0006_contract_customer'),
        ('ingestion', '0001_initial'),
        ('owners', '0003_alter_directorship_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personsourceidentity',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_identities', to='owners.personidentity'),
        ),
        migrations.AddField(
            model_name='personsourceidentity',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.supplier'),
        ),
        migrations.AddField(
            model_name='identitycandidate',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='left_candidates', to='ingestion.personsourceidentity'),
        ),
        migrations.AddField(
            model_name='identitycandidate',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='right_candidates', to='ingestion.personsourceidentity'),
        ),
        migrations.AddField(
            model_name='selectedfact',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_facts', to='companies.supplier'),
        ),
        migrations.AddField(
            model_name='sourcecheckpoint',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.ingestionrun'),
        ),
        migrations.AddField(
            model_name='sourceobservation',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_observations', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='sourceobservation',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='ingestion.ingestionrun'),
        ),
        migrations.AddField(
            model_name='sourceobservation',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_observations', to='companies.supplier'),
        ),
        migrations.AddField(
            model_name='selectedfact',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selected_fields', to='ingestion.sourceobservation'),
        ),
        migrations.AddField(
            model_name='personsourceidentity',
            name='observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingestion.sourceobservation'),
        ),
        migrations.AddConstraint(
            model_name='ingestionissue',
            constraint=models.UniqueConstraint(fields=('run', 'source', 'subject_key', 'stage'), name='ingestion_issue_subject_unique'),
        ),
        migrations.AddConstraint(
            model_name='identitycandidate',
            constraint=models.UniqueConstraint(fields=('left', 'right'), name='ingestion_identity_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='identitycandidate',
            constraint=models.CheckConstraint(condition=models.Q(('left__lt', models.F('right'))), name='ingestion_candidate_ordered'),
        ),
        migrations.AddConstraint(
            model_name='sourcecheckpoint',
            constraint=models.UniqueConstraint(fields=('source', 'stream'), name='ingestion_checkpoint_stream_unique'),
        ),
        migrations.AddIndex(
            model_name='sourceobservation',
            index=models.Index(fields=['source', 'subject_key', '-observed_at'], name='ingestion_observation_lookup'),
        ),
        migrations.AddConstraint(
            model_name='sourceobservation',
            constraint=models.UniqueConstraint(fields=('run', 'source', 'subject_key', 'fingerprint'), name='ingestion_observation_run_unique'),
        ),
        migrations.AddConstraint(
            model_name='selectedfact',
            constraint=models.UniqueConstraint(fields=('supplier', 'field'), name='ingestion_selected_field_unique'),
        ),
        migrations.AddConstraint(
            model_name='personsourceidentity',
            constraint=models.UniqueConstraint(fields=('source', 'source_key'), name='ingestion_person_source_unique'),
        ),
    ]
