# Generated by Django 6.0.6 on 2026-10-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_isolate_legacy_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitycandidate',
            name='status',
            field=models.CharField(choices=[('pending', 'Needs review'), ('rejected', 'Different people'), ('confirmed', 'Confirmed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ingestionrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('succeeded', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially completed')], db_index=True, default='running', max_length=20),
        ),
    ]
