# Generated by Django 6.0.6 on 2026-10-05 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_supplier_is_customer_supplier_is_supplier'),
        ('ingestion', '0005_english_display_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyKgdState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('kgd_taxpayer', 'Taxpayer registration'), ('kgd_tax_debt', 'Tax arrears')], max_length=40)),
                ('last_successful_observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='successful_kgd_states', to='ingestion.sourceobservation')),
                ('latest_observation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='latest_kgd_states', to='ingestion.sourceobservation')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kgd_states', to='companies.supplier')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('supplier', 'source'), name='ingestion_kgd_company_source_unique')],
            },
        ),
    ]
