# Generated by Django 6.0.6 on 2026-10-07 05:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('graph', '0005_evidenceedge_graphinputstate_graphsnapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('analysis_hash', models.CharField(max_length=64)),
                ('input_hash', models.CharField(max_length=64)),
                ('rules_version', models.CharField(max_length=40)),
                ('as_of', models.DateField()),
                ('inputs', models.JSONField(default=dict)),
                ('findings', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=dict)),
                ('limitations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='graph.riskcluster')),
                ('graph_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analyses', to='graph.graphsnapshot')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reuse_key', models.CharField(max_length=64, unique=True)),
                ('language', models.CharField(default='en', max_length=12)),
                ('provider', models.CharField(max_length=20)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('fallback', 'Template fallback')], max_length=12)),
                ('text', models.TextField()),
                ('presentation', models.JSONField(default=dict)),
                ('usage', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('experimental_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('experimental_evidence', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='explanations', to='ai.analysissnapshot')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnalysisState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ai.analysissnapshot')),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_state', to='graph.riskcluster')),
                ('explanation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ai.explanation')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('input_hash', models.CharField(max_length=64)),
                ('dedup_key', models.CharField(max_length=64)),
                ('as_of', models.DateField()),
                ('options', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('fallback', 'Template fallback'), ('stale', 'Superseded'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('graph_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='graph.graphsnapshot')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ai.analysissnapshot')),
                ('explanation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ai.explanation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='analysissnapshot',
            constraint=models.UniqueConstraint(fields=('cluster', 'version'), name='ai_analysis_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='analysissnapshot',
            constraint=models.UniqueConstraint(fields=('graph_snapshot', 'analysis_hash'), name='ai_analysis_content_unique'),
        ),
        migrations.AddConstraint(
            model_name='analysisjob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running'])), fields=('dedup_key',), name='ai_active_job_unique'),
        ),
    ]
