# Generated by Django 6.0.6 on 2026-10-07 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('graph', '0005_evidenceedge_graphinputstate_graphsnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='graph.riskcluster')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ai.analysisjob')),
            ],
        ),
    ]
