# Generated by Django 6.0.6 on 2026-06-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='iin',
            field=models.CharField(blank=True, db_index=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='owner',
            name='iin',
            field=models.CharField(blank=True, db_index=True, default='', max_length=12),
        ),
    ]
