# Generated by Django 6.0.6 on 2026-10-05 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_supplier_is_customer_supplier_is_supplier'),
        ('ingestion', '0001_initial'),
        ('owners', '0002_alter_director_iin_alter_owner_iin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='directorship',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ownership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='directorship',
            name='identity_status',
            field=models.CharField(default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='directorship',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='directorship',
            name='observed_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directorship',
            name='observed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directorship',
            name='source',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='directorship',
            name='source_observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ingestion.sourceobservation'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownership',
            name='identity_status',
            field=models.CharField(default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='ownership',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ownership',
            name='observed_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownership',
            name='observed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownership',
            name='source',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='ownership',
            name='source_observation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ingestion.sourceobservation'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='share_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='PersonIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_key', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('iin', models.CharField(blank=True, max_length=12)),
                ('is_verified', models.BooleanField(default=False)),
                ('director', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='owners.director')),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='owners.owner')),
            ],
        ),
        migrations.AddField(
            model_name='directorship',
            name='person_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='owners.personidentity'),
        ),
        migrations.AddField(
            model_name='ownership',
            name='person_identity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='owners.personidentity'),
        ),
        migrations.AddConstraint(
            model_name='directorship',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('supplier', 'director'), name='owners_current_directorship_unique'),
        ),
        migrations.AddConstraint(
            model_name='ownership',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('supplier', 'owner'), name='owners_current_ownership_unique'),
        ),
        migrations.AddConstraint(
            model_name='ownership',
            constraint=models.CheckConstraint(condition=models.Q(('share_percent__isnull', True), models.Q(('share_percent__gte', 0), ('share_percent__lte', 100)), _connector='OR'), name='owners_share_percent_bounds'),
        ),
        migrations.AddConstraint(
            model_name='personidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('is_verified', True), models.Q(('iin', ''), _negated=True)), fields=('iin',), name='owners_verified_iin_unique'),
        ),
        migrations.AddConstraint(
            model_name='personidentity',
            constraint=models.CheckConstraint(condition=models.Q(('is_verified', False), models.Q(('iin', ''), _negated=True), _connector='OR'), name='owners_verified_iin_required'),
        ),
    ]
